### PR TITLE
Remove images not used by the site

### PR DESCRIPTION
**Pull request by claudiob**

### CODE REVIEW

**Comment by claudiob** [comment]
On a side note, we are pulling images from third-party websites.

I’d rather have a local copy, in case those sites decide to change their URL.

[Here's an example](https://github.com/rails/rails.github.com/blob/master/screencasts/index.html#L16) and [here's another one](https://github.com/rails/rails.github.com/blob/master/screencasts/index.html#L34).

What do you think?

**Comment by claudiob** [comment]
@rafaelfranca ^

**Comment by rafaelfranca** [comment]
Lets have a local copy of them

**Comment by claudiob** [comment]
:+1: :ribbon:

**Pull request merged**
