### PR TITLE
Fixed "join the community" link on homepage

### PR DESCRIPTION
**Pull request by sonalkr132**
Paragraph tag and anchor tag weren't opened correctly. 

PS: This is first pull request I have ever made, so please help me out if i have done something wrong :/

screenshot from 2015-02-12 12 00 57

### CODE REVIEW

**Comment by carlosantoniodasilva** [comment]
It looks just fine, thanks.

**Comment by arielkirkwood** [comment]
Congrats on your first PR!

**Comment by carlosantoniodasilva** [comment]
:green_heart::yellow_heart::heart::blue_heart::purple_heart:

**Comment by sonalkr132** [comment]
Thanks! Really excited!

**Pull request merged**
